spring:
  application:
    name: otm

  mvc:
    dispatch-options-request: true
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9623
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /otm
    encoding:
      force: true
      charset: UTF-8
      enabled: true

#mybatis-plus:
#  mapper-locations: /mapper/*.xml

logging:
  file:
    name: logs/otm.log

knife4j:
  production: false
  enable: true

